### ISSUE TITLE
What are the parameters to run the maas_train.py file?

### ISSUE THREAD

**Issue by woshihaozhu** [fuankarion/MAAS#1]
![image](https://user-images.githubusercontent.com/35716657/156510143-e9dec371-d23b-4117-a0c2-71c6ede12e4b.png)

The parameters for running the maas_train.py file are not given in the paper.  Can you share the configuration of these parameters?

**Comment by fuankarion** [comment]
Hi
Most of these are the  values reported in the paper:
time_length = 13
speakers = 4
hidden_size = 64
clusters = 3

The stride is missing from the paper, and I think it must either 3 or 4.
